# Generated by Django 2.0.3 on 2018-06-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumbiaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('id_origin', models.CharField(max_length=256)),
                ('id_destination', models.CharField(max_length=256)),
                ('journeys', models.IntegerField()),
                ('people', models.IntegerField()),
                ('shapefile', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DRFData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('id_origin', models.CharField(max_length=256)),
                ('id_destination', models.CharField(max_length=256)),
                ('journeys', models.IntegerField()),
                ('people', models.IntegerField()),
                ('shapefile', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAndCountry',
            fields=[
                ('provider', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=256)),
                ('country_code', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='drfdata',
            name='provider_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicbox.ProviderAndCountry'),
        ),
        migrations.AddField(
            model_name='columbiadata',
            name='provider_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicbox.ProviderAndCountry'),
        ),
    ]
